lab_10/urls.py
from django.urls import path
from .views import *

app_name = 'lab_10'

urlpatterns = [
    path('', index, name = 'index'),
    path('regist/', regist, name = 'regist'),
    path('validate/', validate, name = 'validate'),
    path('unsub/', unsub, name = 'unsub'),

]

lab_6/urls.py
from django.urls import path
from .views import *

app_name = 'lab_6'

urlpatterns = [
    path('', index, name='index'),
    path('add_status/', add_status, name='add_status'),
    path('profile/', profile, name='profile'),
]

lab_8/urls.py
from django.urls import path
from .views import *

app_name = 'lab_8'

urlpatterns = [
    path('', index, name='index'),
]

lab_9/urls.py
from django.urls import path
from .views import *

app_name = 'lab_9'

urlpatterns = [
    path('', index, name = 'index'),
    path('search/', search, name = 'search'),
]

ppw_lab_tdd/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('lab_6/', include('lab_6.urls')),
    path('lab_8/', include('lab_8.urls')),
    path('lab_9/', include('lab_9.urls')),
    path('lab_10/', include('lab_10.urls')),
]

lab_10/models.py
from django.db import models

class User(models.Model):
    name = models.CharField(max_length = 50)
    email = models.CharField(max_length = 50)
    password = models.CharField(max_length = 50)

    def __str__(self):
        return self.name

lab_6/models.py
from django.db import models
from datetime import datetime

class Status(models.Model) :
    status = models.CharField(max_length = 300)
    date = models.DateTimeField(default=datetime.now())

lab_8/models.py
from django.db import models

# Create your models here.

lab_9/models.py
from django.db import models

# Create your models here.

lab_10/forms.py
from django import forms

class RegistrationForm(forms.Form):
    name = forms.CharField(label = "Name", max_length = 50, widget = forms.TextInput(
        attrs = {
            'class': 'form-attr name-content',
            'oninput': 'checkValid()',
            'placeholder': 'Your Name',
            'required': True,
        }
    ))

    email = forms.EmailField(label = "E-mail", widget = forms.EmailInput(
        attrs = {
            'class': 'form-attr email-content',
            'oninput': 'checkValid()',
            'required': True,
            'placeholder': 'name@email.com',
        }
    ))

    password = forms.CharField(label = "Password", widget = forms.PasswordInput(
        attrs = {
            'class': 'form-attr password-content',
            'oninput': 'checkValid()',
            'required': True,
            'placeholder': 'Password',
        }
    ))

lab_6/forms.py
from django import forms
from . import models

class StatusForm(forms.Form):
    status = forms.CharField(label = 'Status ', max_length=300, widget=forms.TextInput(attrs = {
        'placeholder' : 'New Status',
        'required' : True,
    }))

lab_10/views.py
from django.shortcuts import render
from .forms import RegistrationForm
from .models import User
from django.http import JsonResponse
import json

def index(req):
    form = RegistrationForm()

    users = list(User.objects.all())
    return render(req, 'lab_10/index.html', {'form': form, 'users' : users})

def regist(req):
    if req.method == 'POST' and req.is_ajax():
        req = json.loads(req.body)

        new_user = User()
        new_user.name = req['name']
        new_user.email = req['email']
        new_user.password = req['password']
        new_user.save()

        return JsonResponse({'form_is_posted' : True})

def validate(req):
    if req.method == 'POST' and req.is_ajax():
        req = json.loads(req.body)

        is_exist = False
        is_valid = False

        if User.objects.filter(email = req['email']).first():
            is_exist = True

        form = RegistrationForm({'name': req['name'], 'password': req['password'], 'email': req['email']})

        if form.is_valid():
            is_valid = True

        return JsonResponse({'email_is_exist' : is_exist, 'form_is_valid': is_valid})

def unsub(req):
    if req.method == 'POST' and req.is_ajax():
        req = json.loads(req.body)

        print(req)
        pass_match = False
        email_found = False

        user = User.objects.filter(email = req['email']).first()

        if user:
            email_found = True
            if user.password == req['password']:
                pass_match = True
                user.delete()

        return JsonResponse({'pass_match' : pass_match, 'email_found' : email_found})
        
            



        


        

lab_6/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from .models import Status
from .forms import StatusForm
from datetime import datetime

def index(req):
    statuses = Status.objects.all()
    form = StatusForm()
    response = {'form' : form, 'statuses' : statuses}
    return render(req, 'lab_6/index.html', response)

def add_status(req):
    if req.method == 'POST':
        form = StatusForm(req.POST)
        if form.is_valid():
            statusObj = Status()
            statusObj.status = form.cleaned_data['status']
            statusObj.date = datetime.now()

            statusObj.save()
        return redirect('lab_6:index')

def profile(req):
    return render(req, 'lab_6/profile.html',)

lab_8/views.py
from django.shortcuts import render

def index(req):
    return render(req,'lab_8/index.html')

lab_9/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

def index(req):
    
    if req.method == 'POST' and req.is_ajax():
        response = json.loads(req.body)
        state = response['state']
        count = int(response['count'])
        
        if state == 'True':
            count -= 1
            state = 'False'
        else:
            count += 1
            state = 'True'
        return JsonResponse({'count' : str(count), 'state' : state})
    else:
        response = requests.get('https://www.googleapis.com/books/v1/volumes?q=quilting')
        data = response.json()
        
        return render(req, 'lab_9/index.html', {'book_data' : data['items']})

def search(req):

    if req.method == 'POST' and req.is_ajax():
        response = json.loads(req.body)
        key = response['key']

        key_url = 'https://www.googleapis.com/books/v1/volumes?q=' + key

        response = requests.get(key_url)
        key_json = response.json()

        return JsonResponse({'data' : key_json['items']})

ppw_lab_tdd/views.py
from django.shortcuts import redirect

def index(req):
    return redirect('/lab_10/')

lab_10/templates/lab_10/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Story 10</title>
    <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel = "stylesheet" href = "{% static 'lab_10/style.css' %}"></head>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src = "{% static 'lab_10/script.js' %}" type = "text/javascript"></script>
<body>
    <div class = "container">
        <div class = "parent">
            <div class = "child">
                <h1 id = "banner">Subscribe Now!</h1>
                <form method="POST" action="" id = "form-sub">
                    {% csrf_token %}
                    {% for field in form.visible_fields %}
                        <div class = "form-field">
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <p hidden id = "form-info"></p>
                    <input onclick = "postForm()" disabled type="submit" class="btn btn-sm btn-secondary" id="submit-button" value = "Subscribe">
                </form>
                <button type = "button" data-toggle="modal" id = "unsub-trigger" data-target="#unsub-modal" class="btn btn-sm btn-secondary">Unsubscribe</button>
                    
                <div class="modal fade" id="unsub-modal" tabindex="-1" role="dialog" aria-labelledby="modal-center" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="unsub-modal-title">Unsubscribe?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form method="POST" id = "form-unsub" action="">
                                    {% csrf_token %}
                                    <div class = "form-field">
                                        {{ form.email.label_tag }}
                                        {{ form.email}}
                                    </div>
                                    <div class = "form-field">
                                        {{ form.password.label_tag }}
                                        {{ form.password}}
                                    </div>
                                    <p hidden id = "form-info-2"></p>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button onclick = "unsubscribe()" type="button" class="btn btn-danger">Unsubscribe</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

lab_6/templates/lab_6/index.html
<!doctype html>
{% load static %}
<html lang="en-US">
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link rel = "stylesheet" href = "{% static "lab_6/style.css" %}">
        <title>Hello!</title>
    </head>
    <body>
        <div class = "container">
            <header class="text-center">
                <h1>Hello, Apa kabar?</h1>
                <a href = "{% url 'lab_6:profile' %}"><h1>Kenalan Yuk!</h1></a>
            </header>

            <div class = "card">
                <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#formModal">Create Status</button>

                <div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="modalCenter" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title black-text" id="modalCenter">Create New Status</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body black-text">
                                <form method="POST" action="{% url 'lab_6:add_status' %}">
                                    {% csrf_token %}
                                    {{ form }}
                                    <div class="modal-footer">
                                        <input type="submit" class="btn btn-light">
                                        <button type="button" class="btn btn-dark" data-dismiss="modal">Back</button>
                                    </div>
                                </form>
                            </div>
                            
                        </div>
                    </div>
                </div>

            </div>

            <div class = "row">
                {% for status in statuses %}
                <div class = "col-md-5 text-center black-bg-opacity-80 border-rounded border-solid-blue-dark white-text" id = "status-content">
                    <p>{{status.status}}</p>
                    <p>{{status.date}}</p>
                </div>
                {% endfor %}
            </div>
        </div>

        
    </body>
</html>

lab_6/templates/lab_6/profile.html
<!doctype html>
{% load static %}
<html lang="en-US">
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link rel = "stylesheet" href = "{% static "lab_6/style.css" %}">
        <title>Hello!</title>
    </head>
    <body>
        <div class ="container">
            <div class ="parent">
                <div>
                    <h1>Hello, Apa Kabar?</h1>
                    <h1>Nama saya Josh</h1>
                    <h1>Nama mu?</h1>
                </div>
            </div>
        </div>
    </body>

lab_8/templates/lab_8/index.html
/<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel = "stylesheet" href = "{% static 'lab_8/style.css' %}">
    <link id = "theme" rel = "stylesheet" href = "{% static 'lab_8/theme-1.css' %}">
    
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.6/dist/loadingoverlay.min.js"></script>
    <script src = "{% static 'lab_8/script.js' %}" type = "text/javascript"></script>
    <script src = "{% static 'lab_8/accordion_src.js' %}" type = "text/javascript"></script>
    
    <title>Story 8</title>  
</head>
<body>
    <div class = "container">
        <div class = "parent">
            <div>
                <h1>Hello, Apa Kabar?</h1>
                <h1>Nama Saya sudz</h1>
                <button onclick="changeTheme()" class = "btn btn-dark" id = "theme-changer">Change Theme</button>
                <h6>Scroll down</h6>
                <h6>for Accordion</h6>
            </div>
        </div>

        <div class = "parent">
            <div class = "row">
                <div class = "col-sm">
                    <h2 class = "title">Aktivitas</h2>
                    <div class = "accordion">
                        <h4>Berbagi</h4>
                        <div>CONTENT 1</div>
                        <h4>Bersama</h4>
                        <div>CONTENT 2</div>
                        <h4>Di Pizza Hut</h4>
                        <div>CONTENT 3</div>
                    </div>
                </div>

                <div class = "col-sm">
                    <h2 class = "title">Pengalaman</h2>
                    <div class = "accordion">
                        <h4>Belajar</h4>
                        <div>CONTENT 1</div>
                        <h4>Bersama</h4>
                        <div>CONTENT 2</div>
                        <h4>Kak Pewe</h4>
                        <div>CONTENT 3</div>
                    </div>
                </div>

                <div class = "col-sm">
                    <h2 class = "title">Prestasi</h2>
                    <div class = "accordion">
                        <h4>Lulus</h4>
                        <div>CONTENT 1</div>
                        <h4>PPW</h4>
                        <div>CONTENT 2</div>
                        <h4>2018</h4>
                        <div>CONTENT 3</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

lab_9/templates/lab_9/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel = "stylesheet" href = "{% static 'lab_9/style.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src = "{% static 'lab_9/script.js' %}" type = "text/javascript"></script>
    <title>Story 9</title>
</head>
<body>
    <div class = "container">
        <div class = "parent">
            <div>
                <form method="POST">
                    {% csrf_token %}
                    <div class="input-group input-group-sm sm-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">Search Book</span>
                        </div>
                        <input placeholder = "Search Book. Press enter to search."type="text" id = "search" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                    </div>
                </form>
                <table>
                    <thead>
                        <tr>
                            <th>Book Title</th>
                            <th>Authors</th>
                            <th>Publishers</th>
                            <th>Published Date</th>
                            <th>Add to Favorites</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for book in book_data %}
                            <tr>
                                <td>{{ book.volumeInfo.title }}</td>
                                <td>
                                {% for author in book.volumeInfo.authors %}
                                    {{ author }} <br>
                                {% endfor %}
                                </td>
                                <td>{{ book.volumeInfo.publisher }}</td>
                                <td>{{ book.volumeInfo.publishedDate }}</td>
                                <form id = "favorite" method="POST">
                                    {% csrf_token %}
                                    <td><button value = "False" type = "button" onclick = "favoriteAction(this)" class = "btn btn-light btn-sm">Favorite</button></td>
                                </form>
                            </tr>
                        {% endfor %}
                    
                    </tbody>
                </table>
                
                <h4>Favorites : <span id = 'counter'>0</span></h4>
            </div>
        </div>
    </div>
</body>
</html>